/**
 * The brand mark: the lens.
 *
 * Written by `scripts/generate-icons.mjs` from the drawing in
 * `scripts/brand-mark.mjs`. Do not edit this file by hand.
 *
 * A disc with a smaller disc cut out of it, up and to the right, so what is
 * left is a crescent that thins toward the bite. The cut is an even-odd hole
 * in one path, not a second shape in the ground colour, so the mark holds on
 * any ground. Fill the path with `fill-rule: evenodd`.
 *
 * `components/landing/Logo.tsx` and `app/opengraph-image.tsx` draw this path;
 * the icons beside it are raster copies of the same drawing.
 *
 * The path is drawn in a 48 by 48 box, on a disc of radius
 * 15 at (24, 24).
 */
export const MARK_PATH =
  'M9 24a15 15 0 1 0 30 0a15 15 0 1 0 -30 0ZM21 20.25a6.75 6.75 0 1 0 13.5 0a6.75 6.75 0 1 0 -13.5 0Z'

/** The box the path is drawn in. */
export const MARK_VIEWBOX = '0 0 48 48'

/** The tile's corner in box units. 12 of 48 is the 8px icon radius at 32px. */
export const MARK_TILE_RADIUS = 12

/**
 * The lens is lit from the top, the way every band on the page is: paper at
 * 1 where the light lands and 0.95 at the foot. On ink that runs from
 * 17.8:1 down to 16.0:1, so the whole crescent stays well clear of
 * the 3:1 a graphic needs.
 */
export const MARK_LIT = 1
export const MARK_SHADE = 0.95

/**
 * Where that light runs, in box units: the lens's own top edge down to its
 * bottom one. Draw the gradient on the x axis at 24.
 */
export const MARK_LIT_FROM = 9
export const MARK_LIT_TO = 39
export const MARK_CENTRE = 24
