/**
 * Draws the brand mark and writes every file that carries it:
 *
 *   lib/brand-mark.ts   the path, which the landing and the share card import
 *   app/icon.svg        the mark on its disc, for browsers that take an SVG
 *   app/favicon.ico     16, 32 and 48px, for browsers that still ask for it
 *   app/apple-icon.png  180px, for the iOS home screen
 *
 * `scripts/brand-mark.mjs` holds the drawing and its dials. Change a dial
 * there, then run:
 *   node scripts/generate-icons.mjs
 *
 * Every file above is written by this script. None is edited by hand.
 */
import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import sharp from 'sharp'

import { markPath } from './brand-mark.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const BECK = '#a3202f'
const PAPER = '#ffffff'
const MARK_VIEWBOX = '0 0 64 64'
const MARK_PATH = markPath()

/** The mark on a disc, or on a full square for a tile that gets masked. */
function markSvg({ ground }) {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${MARK_VIEWBOX}" width="64" height="64" shape-rendering="geometricPrecision">` +
    `<title>Contract Lens</title>` +
    (ground === 'disc'
      ? `<circle cx="32" cy="32" r="32" fill="${BECK}"/>`
      : `<rect width="64" height="64" fill="${BECK}"/>`) +
    `<path d="${MARK_PATH}" fill="${PAPER}"/>` +
    `</svg>\n`
  )
}

/** The .ico container, with each size stored as a PNG. */
function buildIco(images) {
  const header = Buffer.alloc(6)
  header.writeUInt16LE(0, 0) // reserved
  header.writeUInt16LE(1, 2) // 1 = icon
  header.writeUInt16LE(images.length, 4)

  let offset = 6 + images.length * 16
  const entries = images.map(({ size, png }) => {
    const entry = Buffer.alloc(16)
    entry.writeUInt8(size >= 256 ? 0 : size, 0) // 0 stands for 256
    entry.writeUInt8(size >= 256 ? 0 : size, 1)
    entry.writeUInt8(0, 2) // palette size, 0 for true colour
    entry.writeUInt8(0, 3) // reserved
    entry.writeUInt16LE(1, 4) // colour planes
    entry.writeUInt16LE(32, 6) // bits per pixel
    entry.writeUInt32LE(png.length, 8)
    entry.writeUInt32LE(offset, 12)
    offset += png.length
    return entry
  })

  return Buffer.concat([header, ...entries, ...images.map((image) => image.png)])
}

await writeFile(
  join(root, 'lib/brand-mark.ts'),
  `/**
 * The brand mark: the section sign, drawn.
 *
 * Written by \`scripts/generate-icons.mjs\` from the drawing in
 * \`scripts/brand-mark.mjs\`. Do not edit this file by hand.
 *
 * The sign is not set in a typeface. It is cut for the disc, so the stroke
 * still holds at 16px in a browser tab, where a typeset § fills in and reads
 * as a smudge. \`components/landing/Logo.tsx\` and \`app/opengraph-image.tsx\`
 * draw this path; the icons beside it are raster copies of the same drawing.
 *
 * The path is drawn in a 64 by 64 box, on a disc of radius 32 at (32, 32).
 */
export const MARK_PATH =
  '${MARK_PATH}'

/** The box the path is drawn in. */
export const MARK_VIEWBOX = '${MARK_VIEWBOX}'
`
)

const disc = markSvg({ ground: 'disc' })
await writeFile(join(root, 'app/icon.svg'), disc)

const icoSizes = [16, 32, 48]
const icoImages = await Promise.all(
  icoSizes.map(async (size) => ({
    size,
    png: await sharp(Buffer.from(disc), { density: 2400 }).resize(size, size).png().toBuffer(),
  }))
)
await writeFile(join(root, 'app/favicon.ico'), buildIco(icoImages))

// iOS masks the tile to a rounded square and puts it on the wallpaper, so the
// red bleeds to the edge instead of sitting in a disc. The mark also grows,
// because a tile leaves less room round the edge than a disc does.
const tile = markSvg({ ground: 'square' }).replace(
  `<path d="${MARK_PATH}"`,
  `<path transform="translate(32 32) scale(1.06) translate(-32 -32)" d="${MARK_PATH}"`
)
await writeFile(
  join(root, 'app/apple-icon.png'),
  await sharp(Buffer.from(tile), { density: 2400 }).resize(180, 180).png().toBuffer()
)

console.log('Wrote lib/brand-mark.ts, app/icon.svg, app/favicon.ico and app/apple-icon.png')
